services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    command:
      - "--api.dashboard=true" # Active le dashboard
      - "--providers.docker=true" # Permet à Traefik de détecter les containers Docker
      - "--providers.docker.exposedbydefault=false" # Evite d'exposer tous les containers par défaut
      - "--entrypoints.web.address=:80" # Trafic HTTP
      - "--entrypoints.websecure.address=:443" # Trafic HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure" # Redirection HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https" # Redirection HTTP -> HTTPS
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true" # Challenge TLS pour Let's Encrypt
      - "--certificatesresolvers.letsencrypt.acme.email=carthographie@outlook.fr" # Ton email Let's Encrypt
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json" # Stockage des certificats
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # DASHBOARD
    networks:
      - netcartho
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      # Route pour le dashboard
      - "traefik.http.routers.dashboard.rule=Host(`traefik.carthographie.fr`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      # Middleware pour l'authentification basique (optionnel mais recommandé)
      # - "traefik.http.middlewares.auth.basicauth.users=admin:$apr1$9gzDnaoG$R7Nnpcr5w0wRDTo0.Lcn20" # Générez votre propre hash
      # - "traefik.http.routers.dashboard.middlewares=auth"
      # Headers de sécurité
      # - "traefik.http.middlewares.security-headers.headers.stsSeconds=31536000"
      # - "traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true"
      # - "traefik.http.middlewares.security-headers.headers.stsPreload=true"
      # - "traefik.http.middlewares.security-headers.headers.customFrameOptionsValue=SAMEORIGIN"
      # - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      # - "traefik.http.middlewares.security-headers.headers.referrerPolicy=strict-origin-when-cross-origin"
      # - "traefik.http.middlewares.security-headers.headers.permissionsPolicy=camera=(), microphone=(), geolocation=(), payment=()"

      # Appliquer les headers de sécurité au dashboard
      # - "traefik.http.routers.dashboard.middlewares=security-headers"

  web:
    image: carthographie/lyrics-slide-show:latest
    command: >
      sh -c "scripts/wait_for_db.sh &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn lyrics_slide_show.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - netcartho
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`www.carthographie.fr`)"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - netcartho

  n8n:
    image: n8nio/n8n
    environment:
      - N8N_PATH=/n8n
      - N8N_EDITOR_BASE_URL=https://n8n.carthographie.fr/
      - VUE_APP_URL_BASE_API=https://n8n.carthographie.fr/
      - WEBHOOK_URL=https://n8n.carthographie.fr/
      - N8N_HOST=n8n
      - N8N_PORT=5678
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n_files:/files
    networks:
      - netcartho
    restart: always
    labels:
      - "traefik.enable=true"
      # N8N
      - "traefik.http.routers.n8n.rule=Host(`n8n.carthographie.fr`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

networks:
  netcartho:
    external: true

volumes:
  letsencrypt:
  mysql_data: {}
